CREATE DATABASE languages;
CREATE DATABASE webDevelopment CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS Frameworks CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS languages CHARACTER SET utf8;
DROP DATABASE languages;
DROP DATABASE IF EXISTS Frameworks;
DROP DATABASE IF EXISTS languages;
